# config/deploy.yml — common to all environments
service: 1stapp
image: higor-franco/1stapp

servers:
  web:
    proxy:
      app_port: 80
      forward_headers: false
      healthcheck:
        path: /up
        interval: 10
        threshold: 3

ssh:
  user: root
  keys_only: true

registry:
  server: ghcr.io
  username:
    - REPO_OWNER
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  cache:
    type: gha
    options: mode=max

env:
  clear:
    PORT: "80"

readiness_delay: 15
deploy_timeout: 180
drain_timeout: 30
