// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bio_pages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBioPageByUserID = `-- name: GetBioPageByUserID :one
SELECT id, user_id, whatsapp, instagram, facebook, tiktok, youtube, extra_links, published, created_at, updated_at FROM bio_pages WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetBioPageByUserID(ctx context.Context, userID pgtype.UUID) (BioPage, error) {
	row := q.db.QueryRow(ctx, getBioPageByUserID, userID)
	var i BioPage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Whatsapp,
		&i.Instagram,
		&i.Facebook,
		&i.Tiktok,
		&i.Youtube,
		&i.ExtraLinks,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBioPage = `-- name: UpsertBioPage :one
INSERT INTO bio_pages (user_id, whatsapp, instagram, facebook, tiktok, youtube, extra_links, published, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
ON CONFLICT (user_id) DO UPDATE SET
    whatsapp    = EXCLUDED.whatsapp,
    instagram   = EXCLUDED.instagram,
    facebook    = EXCLUDED.facebook,
    tiktok      = EXCLUDED.tiktok,
    youtube     = EXCLUDED.youtube,
    extra_links = EXCLUDED.extra_links,
    published   = EXCLUDED.published,
    updated_at  = NOW()
RETURNING id, user_id, whatsapp, instagram, facebook, tiktok, youtube, extra_links, published, created_at, updated_at
`

type UpsertBioPageParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Whatsapp   string      `json:"whatsapp"`
	Instagram  string      `json:"instagram"`
	Facebook   string      `json:"facebook"`
	Tiktok     string      `json:"tiktok"`
	Youtube    string      `json:"youtube"`
	ExtraLinks string      `json:"extra_links"`
	Published  bool        `json:"published"`
}

func (q *Queries) UpsertBioPage(ctx context.Context, arg UpsertBioPageParams) (BioPage, error) {
	row := q.db.QueryRow(ctx, upsertBioPage,
		arg.UserID,
		arg.Whatsapp,
		arg.Instagram,
		arg.Facebook,
		arg.Tiktok,
		arg.Youtube,
		arg.ExtraLinks,
		arg.Published,
	)
	var i BioPage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Whatsapp,
		&i.Instagram,
		&i.Facebook,
		&i.Tiktok,
		&i.Youtube,
		&i.ExtraLinks,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
