// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (user_id, vindi_bill_id, amount, status, due_at, paid_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, vindi_bill_id, amount, status, due_at, paid_at, created_at
`

type CreateInvoiceParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	VindiBillID pgtype.Int4        `json:"vindi_bill_id"`
	Amount      int32              `json:"amount"`
	Status      string             `json:"status"`
	DueAt       pgtype.Timestamptz `json:"due_at"`
	PaidAt      pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.UserID,
		arg.VindiBillID,
		arg.Amount,
		arg.Status,
		arg.DueAt,
		arg.PaidAt,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VindiBillID,
		&i.Amount,
		&i.Status,
		&i.DueAt,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvoicesByUserID = `-- name: ListInvoicesByUserID :many
SELECT id, user_id, vindi_bill_id, amount, status, due_at, paid_at, created_at FROM invoices WHERE user_id = $1 ORDER BY created_at DESC LIMIT 20
`

func (q *Queries) ListInvoicesByUserID(ctx context.Context, userID pgtype.UUID) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VindiBillID,
			&i.Amount,
			&i.Status,
			&i.DueAt,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :one
UPDATE invoices SET status = $2, paid_at = $3
WHERE vindi_bill_id = $1
RETURNING id, user_id, vindi_bill_id, amount, status, due_at, paid_at, created_at
`

type UpdateInvoiceStatusParams struct {
	VindiBillID pgtype.Int4        `json:"vindi_bill_id"`
	Status      string             `json:"status"`
	PaidAt      pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoiceStatus, arg.VindiBillID, arg.Status, arg.PaidAt)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VindiBillID,
		&i.Amount,
		&i.Status,
		&i.DueAt,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}
