// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLogoByUserID = `-- name: GetLogoByUserID :one
SELECT id, user_id, svg_1, svg_2, svg_3, selected_index, created_at, updated_at FROM logos WHERE user_id = $1
`

func (q *Queries) GetLogoByUserID(ctx context.Context, userID pgtype.UUID) (Logo, error) {
	row := q.db.QueryRow(ctx, getLogoByUserID, userID)
	var i Logo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Svg1,
		&i.Svg2,
		&i.Svg3,
		&i.SelectedIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLogoSelected = `-- name: UpdateLogoSelected :one
UPDATE logos
SET selected_index = $2, updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, svg_1, svg_2, svg_3, selected_index, created_at, updated_at
`

type UpdateLogoSelectedParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	SelectedIndex int32       `json:"selected_index"`
}

func (q *Queries) UpdateLogoSelected(ctx context.Context, arg UpdateLogoSelectedParams) (Logo, error) {
	row := q.db.QueryRow(ctx, updateLogoSelected, arg.UserID, arg.SelectedIndex)
	var i Logo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Svg1,
		&i.Svg2,
		&i.Svg3,
		&i.SelectedIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLogo = `-- name: UpsertLogo :one
INSERT INTO logos (user_id, svg_1, svg_2, svg_3, selected_index)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE
SET svg_1 = $2, svg_2 = $3, svg_3 = $4, selected_index = $5, updated_at = NOW()
RETURNING id, user_id, svg_1, svg_2, svg_3, selected_index, created_at, updated_at
`

type UpsertLogoParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	Svg1          string      `json:"svg_1"`
	Svg2          string      `json:"svg_2"`
	Svg3          string      `json:"svg_3"`
	SelectedIndex int32       `json:"selected_index"`
}

func (q *Queries) UpsertLogo(ctx context.Context, arg UpsertLogoParams) (Logo, error) {
	row := q.db.QueryRow(ctx, upsertLogo,
		arg.UserID,
		arg.Svg1,
		arg.Svg2,
		arg.Svg3,
		arg.SelectedIndex,
	)
	var i Logo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Svg1,
		&i.Svg2,
		&i.Svg3,
		&i.SelectedIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
