// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BioPage struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Whatsapp   string             `json:"whatsapp"`
	Instagram  string             `json:"instagram"`
	Facebook   string             `json:"facebook"`
	Tiktok     string             `json:"tiktok"`
	Youtube    string             `json:"youtube"`
	ExtraLinks string             `json:"extra_links"`
	Published  bool               `json:"published"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Invoice struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	VindiBillID pgtype.Int4        `json:"vindi_bill_id"`
	Amount      int32              `json:"amount"`
	Status      string             `json:"status"`
	DueAt       pgtype.Timestamptz `json:"due_at"`
	PaidAt      pgtype.Timestamptz `json:"paid_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Logo struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Svg1          string             `json:"svg_1"`
	Svg2          string             `json:"svg_2"`
	Svg3          string             `json:"svg_3"`
	SelectedIndex int32              `json:"selected_index"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type OctadeskConfig struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	WidgetCode     string             `json:"widget_code"`
	WhatsappNumber string             `json:"whatsapp_number"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type OnboardingStep struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	StepName    string             `json:"step_name"`
	Completed   bool               `json:"completed"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PaymentAddon struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	VindiApiKey   string             `json:"vindi_api_key"`
	ServiceName   string             `json:"service_name"`
	ServiceAmount int32              `json:"service_amount"`
	ServiceType   string             `json:"service_type"`
	Active        bool               `json:"active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type SeoConfig struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	Keywords           []string           `json:"keywords"`
	CompetitorDomains  []string           `json:"competitor_domains"`
	DataForSeoLogin    string             `json:"data_for_seo_login"`
	DataForSeoPassword string             `json:"data_for_seo_password"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type SeoReport struct {
	ID      pgtype.UUID        `json:"id"`
	UserID  pgtype.UUID        `json:"user_id"`
	RunAt   pgtype.Timestamptz `json:"run_at"`
	Results string             `json:"results"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Site struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Slug                string             `json:"slug"`
	BusinessName        string             `json:"business_name"`
	BusinessDescription string             `json:"business_description"`
	ColorPalette        string             `json:"color_palette"`
	HtmlContent         string             `json:"html_content"`
	Published           bool               `json:"published"`
	CustomDomain        pgtype.Text        `json:"custom_domain"`
	GenerationCount     int32              `json:"generation_count"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type SiteVersion struct {
	ID          pgtype.UUID        `json:"id"`
	SiteID      pgtype.UUID        `json:"site_id"`
	VersionNum  int32              `json:"version_num"`
	HtmlContent string             `json:"html_content"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	VindiCustomerID     pgtype.Int4        `json:"vindi_customer_id"`
	VindiSubscriptionID pgtype.Int4        `json:"vindi_subscription_id"`
	Status              string             `json:"status"`
	CurrentPeriodEnd    pgtype.Timestamptz `json:"current_period_end"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Plan         string             `json:"plan"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
