// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: octadesk.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOctadeskByUserID = `-- name: GetOctadeskByUserID :one
SELECT id, user_id, widget_code, whatsapp_number, active, created_at, updated_at FROM octadesk_configs WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetOctadeskByUserID(ctx context.Context, userID pgtype.UUID) (OctadeskConfig, error) {
	row := q.db.QueryRow(ctx, getOctadeskByUserID, userID)
	var i OctadeskConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WidgetCode,
		&i.WhatsappNumber,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOctadesk = `-- name: UpsertOctadesk :one
INSERT INTO octadesk_configs (user_id, widget_code, whatsapp_number, active, updated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (user_id) DO UPDATE SET
    widget_code     = EXCLUDED.widget_code,
    whatsapp_number = EXCLUDED.whatsapp_number,
    active          = EXCLUDED.active,
    updated_at      = NOW()
RETURNING id, user_id, widget_code, whatsapp_number, active, created_at, updated_at
`

type UpsertOctadeskParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	WidgetCode     string      `json:"widget_code"`
	WhatsappNumber string      `json:"whatsapp_number"`
	Active         bool        `json:"active"`
}

func (q *Queries) UpsertOctadesk(ctx context.Context, arg UpsertOctadeskParams) (OctadeskConfig, error) {
	row := q.db.QueryRow(ctx, upsertOctadesk,
		arg.UserID,
		arg.WidgetCode,
		arg.WhatsappNumber,
		arg.Active,
	)
	var i OctadeskConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WidgetCode,
		&i.WhatsappNumber,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
