// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: onboarding_steps.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOnboardingStepsByUserID = `-- name: GetOnboardingStepsByUserID :many
SELECT id, user_id, step_name, completed, completed_at, created_at FROM onboarding_steps WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) GetOnboardingStepsByUserID(ctx context.Context, userID pgtype.UUID) ([]OnboardingStep, error) {
	rows, err := q.db.Query(ctx, getOnboardingStepsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OnboardingStep
	for rows.Next() {
		var i OnboardingStep
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StepName,
			&i.Completed,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOnboardingStep = `-- name: UpsertOnboardingStep :one
INSERT INTO onboarding_steps (user_id, step_name, completed, completed_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, step_name) DO UPDATE SET
    completed    = EXCLUDED.completed,
    completed_at = EXCLUDED.completed_at
RETURNING id, user_id, step_name, completed, completed_at, created_at
`

type UpsertOnboardingStepParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	StepName    string             `json:"step_name"`
	Completed   bool               `json:"completed"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpsertOnboardingStep(ctx context.Context, arg UpsertOnboardingStepParams) (OnboardingStep, error) {
	row := q.db.QueryRow(ctx, upsertOnboardingStep,
		arg.UserID,
		arg.StepName,
		arg.Completed,
		arg.CompletedAt,
	)
	var i OnboardingStep
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StepName,
		&i.Completed,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}
