// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_addons.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPaymentAddonByUserID = `-- name: GetPaymentAddonByUserID :one
SELECT id, user_id, vindi_api_key, service_name, service_amount, service_type, active, created_at, updated_at FROM payment_addons WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetPaymentAddonByUserID(ctx context.Context, userID pgtype.UUID) (PaymentAddon, error) {
	row := q.db.QueryRow(ctx, getPaymentAddonByUserID, userID)
	var i PaymentAddon
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VindiApiKey,
		&i.ServiceName,
		&i.ServiceAmount,
		&i.ServiceType,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPaymentAddon = `-- name: UpsertPaymentAddon :one
INSERT INTO payment_addons (user_id, vindi_api_key, service_name, service_amount, service_type, active, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (user_id) DO UPDATE SET
    vindi_api_key  = EXCLUDED.vindi_api_key,
    service_name   = EXCLUDED.service_name,
    service_amount = EXCLUDED.service_amount,
    service_type   = EXCLUDED.service_type,
    active         = EXCLUDED.active,
    updated_at     = NOW()
RETURNING id, user_id, vindi_api_key, service_name, service_amount, service_type, active, created_at, updated_at
`

type UpsertPaymentAddonParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	VindiApiKey   string      `json:"vindi_api_key"`
	ServiceName   string      `json:"service_name"`
	ServiceAmount int32       `json:"service_amount"`
	ServiceType   string      `json:"service_type"`
	Active        bool        `json:"active"`
}

func (q *Queries) UpsertPaymentAddon(ctx context.Context, arg UpsertPaymentAddonParams) (PaymentAddon, error) {
	row := q.db.QueryRow(ctx, upsertPaymentAddon,
		arg.UserID,
		arg.VindiApiKey,
		arg.ServiceName,
		arg.ServiceAmount,
		arg.ServiceType,
		arg.Active,
	)
	var i PaymentAddon
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VindiApiKey,
		&i.ServiceName,
		&i.ServiceAmount,
		&i.ServiceType,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
