// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seo.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSEOReport = `-- name: CreateSEOReport :one
INSERT INTO seo_reports (user_id, results)
VALUES ($1, $2)
RETURNING id, user_id, run_at, results
`

type CreateSEOReportParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Results string      `json:"results"`
}

func (q *Queries) CreateSEOReport(ctx context.Context, arg CreateSEOReportParams) (SeoReport, error) {
	row := q.db.QueryRow(ctx, createSEOReport, arg.UserID, arg.Results)
	var i SeoReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunAt,
		&i.Results,
	)
	return i, err
}

const getSEOConfigByUserID = `-- name: GetSEOConfigByUserID :one
SELECT id, user_id, keywords, competitor_domains, data_for_seo_login, data_for_seo_password, created_at, updated_at FROM seo_configs WHERE user_id = $1
`

func (q *Queries) GetSEOConfigByUserID(ctx context.Context, userID pgtype.UUID) (SeoConfig, error) {
	row := q.db.QueryRow(ctx, getSEOConfigByUserID, userID)
	var i SeoConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Keywords,
		&i.CompetitorDomains,
		&i.DataForSeoLogin,
		&i.DataForSeoPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSEOReportsByUserID = `-- name: GetSEOReportsByUserID :many
SELECT id, user_id, run_at, results
FROM seo_reports
WHERE user_id = $1
ORDER BY run_at DESC
LIMIT 10
`

func (q *Queries) GetSEOReportsByUserID(ctx context.Context, userID pgtype.UUID) ([]SeoReport, error) {
	rows, err := q.db.Query(ctx, getSEOReportsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeoReport
	for rows.Next() {
		var i SeoReport
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RunAt,
			&i.Results,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSEOConfig = `-- name: UpsertSEOConfig :one
INSERT INTO seo_configs (user_id, keywords, competitor_domains, data_for_seo_login, data_for_seo_password)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE
SET keywords              = EXCLUDED.keywords,
    competitor_domains    = EXCLUDED.competitor_domains,
    data_for_seo_login    = EXCLUDED.data_for_seo_login,
    data_for_seo_password = EXCLUDED.data_for_seo_password,
    updated_at            = NOW()
RETURNING id, user_id, keywords, competitor_domains, data_for_seo_login, data_for_seo_password, created_at, updated_at
`

type UpsertSEOConfigParams struct {
	UserID             pgtype.UUID `json:"user_id"`
	Keywords           []string    `json:"keywords"`
	CompetitorDomains  []string    `json:"competitor_domains"`
	DataForSeoLogin    string      `json:"data_for_seo_login"`
	DataForSeoPassword string      `json:"data_for_seo_password"`
}

func (q *Queries) UpsertSEOConfig(ctx context.Context, arg UpsertSEOConfigParams) (SeoConfig, error) {
	row := q.db.QueryRow(ctx, upsertSEOConfig,
		arg.UserID,
		arg.Keywords,
		arg.CompetitorDomains,
		arg.DataForSeoLogin,
		arg.DataForSeoPassword,
	)
	var i SeoConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Keywords,
		&i.CompetitorDomains,
		&i.DataForSeoLogin,
		&i.DataForSeoPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
