// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: site_versions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSiteVersion = `-- name: CreateSiteVersion :one
INSERT INTO site_versions (site_id, version_num, html_content)
SELECT $1,
       COALESCE((SELECT MAX(version_num) FROM site_versions WHERE site_id = $1), 0) + 1,
       $2
RETURNING id, site_id, version_num, html_content, created_at
`

type CreateSiteVersionParams struct {
	SiteID      pgtype.UUID `json:"site_id"`
	HtmlContent string      `json:"html_content"`
}

func (q *Queries) CreateSiteVersion(ctx context.Context, arg CreateSiteVersionParams) (SiteVersion, error) {
	row := q.db.QueryRow(ctx, createSiteVersion, arg.SiteID, arg.HtmlContent)
	var i SiteVersion
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.VersionNum,
		&i.HtmlContent,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteVersionHTML = `-- name: GetSiteVersionHTML :one
SELECT html_content FROM site_versions WHERE id = $1 AND site_id = $2
`

type GetSiteVersionHTMLParams struct {
	ID     pgtype.UUID `json:"id"`
	SiteID pgtype.UUID `json:"site_id"`
}

func (q *Queries) GetSiteVersionHTML(ctx context.Context, arg GetSiteVersionHTMLParams) (string, error) {
	row := q.db.QueryRow(ctx, getSiteVersionHTML, arg.ID, arg.SiteID)
	var html_content string
	err := row.Scan(&html_content)
	return html_content, err
}

const getSiteVersionsBySiteID = `-- name: GetSiteVersionsBySiteID :many
SELECT id, site_id, version_num, created_at
FROM site_versions
WHERE site_id = $1
ORDER BY version_num DESC
LIMIT 5
`

type GetSiteVersionsBySiteIDRow struct {
	ID         pgtype.UUID        `json:"id"`
	SiteID     pgtype.UUID        `json:"site_id"`
	VersionNum int32              `json:"version_num"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetSiteVersionsBySiteID(ctx context.Context, siteID pgtype.UUID) ([]GetSiteVersionsBySiteIDRow, error) {
	rows, err := q.db.Query(ctx, getSiteVersionsBySiteID, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSiteVersionsBySiteIDRow
	for rows.Next() {
		var i GetSiteVersionsBySiteIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.VersionNum,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trimSiteVersions = `-- name: TrimSiteVersions :exec
DELETE FROM site_versions sv
WHERE sv.site_id = $1
  AND sv.id NOT IN (
      SELECT sv2.id FROM site_versions sv2
      WHERE sv2.site_id = $1
      ORDER BY sv2.version_num DESC
      LIMIT 5
  )
`

func (q *Queries) TrimSiteVersions(ctx context.Context, siteID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, trimSiteVersions, siteID)
	return err
}
