// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSite = `-- name: CreateSite :one
INSERT INTO sites (user_id, slug, business_name, business_description, color_palette)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, slug, business_name, business_description, color_palette, html_content, published, custom_domain, generation_count, created_at, updated_at
`

type CreateSiteParams struct {
	UserID              pgtype.UUID `json:"user_id"`
	Slug                string      `json:"slug"`
	BusinessName        string      `json:"business_name"`
	BusinessDescription string      `json:"business_description"`
	ColorPalette        string      `json:"color_palette"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.UserID,
		arg.Slug,
		arg.BusinessName,
		arg.BusinessDescription,
		arg.ColorPalette,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.BusinessName,
		&i.BusinessDescription,
		&i.ColorPalette,
		&i.HtmlContent,
		&i.Published,
		&i.CustomDomain,
		&i.GenerationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllPublishedSites = `-- name: GetAllPublishedSites :many
SELECT id, slug, business_name, business_description, updated_at
FROM sites
WHERE published = true
ORDER BY updated_at DESC
`

type GetAllPublishedSitesRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Slug                string             `json:"slug"`
	BusinessName        string             `json:"business_name"`
	BusinessDescription string             `json:"business_description"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAllPublishedSites(ctx context.Context) ([]GetAllPublishedSitesRow, error) {
	rows, err := q.db.Query(ctx, getAllPublishedSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPublishedSitesRow
	for rows.Next() {
		var i GetAllPublishedSitesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.BusinessName,
			&i.BusinessDescription,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSiteBySlug = `-- name: GetSiteBySlug :one
SELECT id, user_id, slug, business_name, business_description, color_palette, html_content, published, custom_domain, generation_count, created_at, updated_at FROM sites WHERE slug = $1
`

func (q *Queries) GetSiteBySlug(ctx context.Context, slug string) (Site, error) {
	row := q.db.QueryRow(ctx, getSiteBySlug, slug)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.BusinessName,
		&i.BusinessDescription,
		&i.ColorPalette,
		&i.HtmlContent,
		&i.Published,
		&i.CustomDomain,
		&i.GenerationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteByUserID = `-- name: GetSiteByUserID :one
SELECT id, user_id, slug, business_name, business_description, color_palette, html_content, published, custom_domain, generation_count, created_at, updated_at FROM sites WHERE user_id = $1
`

func (q *Queries) GetSiteByUserID(ctx context.Context, userID pgtype.UUID) (Site, error) {
	row := q.db.QueryRow(ctx, getSiteByUserID, userID)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.BusinessName,
		&i.BusinessDescription,
		&i.ColorPalette,
		&i.HtmlContent,
		&i.Published,
		&i.CustomDomain,
		&i.GenerationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const slugExists = `-- name: SlugExists :one
SELECT EXISTS(SELECT 1 FROM sites WHERE slug = $1) AS exists
`

func (q *Queries) SlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, slugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateSiteContent = `-- name: UpdateSiteContent :one
UPDATE sites
SET html_content      = $2,
    published         = $3,
    generation_count  = generation_count + 1,
    updated_at        = NOW()
WHERE id = $1
RETURNING id, user_id, slug, business_name, business_description, color_palette, html_content, published, custom_domain, generation_count, created_at, updated_at
`

type UpdateSiteContentParams struct {
	ID          pgtype.UUID `json:"id"`
	HtmlContent string      `json:"html_content"`
	Published   bool        `json:"published"`
}

func (q *Queries) UpdateSiteContent(ctx context.Context, arg UpdateSiteContentParams) (Site, error) {
	row := q.db.QueryRow(ctx, updateSiteContent, arg.ID, arg.HtmlContent, arg.Published)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.BusinessName,
		&i.BusinessDescription,
		&i.ColorPalette,
		&i.HtmlContent,
		&i.Published,
		&i.CustomDomain,
		&i.GenerationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSiteCustomDomain = `-- name: UpdateSiteCustomDomain :one
UPDATE sites SET custom_domain = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, slug, business_name, business_description, color_palette, html_content, published, custom_domain, generation_count, created_at, updated_at
`

type UpdateSiteCustomDomainParams struct {
	ID           pgtype.UUID `json:"id"`
	CustomDomain pgtype.Text `json:"custom_domain"`
}

func (q *Queries) UpdateSiteCustomDomain(ctx context.Context, arg UpdateSiteCustomDomainParams) (Site, error) {
	row := q.db.QueryRow(ctx, updateSiteCustomDomain, arg.ID, arg.CustomDomain)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.BusinessName,
		&i.BusinessDescription,
		&i.ColorPalette,
		&i.HtmlContent,
		&i.Published,
		&i.CustomDomain,
		&i.GenerationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSiteGeneration = `-- name: UpdateSiteGeneration :one
UPDATE sites
SET business_name        = $2,
    business_description = $3,
    color_palette        = $4,
    html_content         = $5,
    generation_count     = generation_count + 1,
    updated_at           = NOW()
WHERE user_id = $1
RETURNING id, user_id, slug, business_name, business_description, color_palette, html_content, published, custom_domain, generation_count, created_at, updated_at
`

type UpdateSiteGenerationParams struct {
	UserID              pgtype.UUID `json:"user_id"`
	BusinessName        string      `json:"business_name"`
	BusinessDescription string      `json:"business_description"`
	ColorPalette        string      `json:"color_palette"`
	HtmlContent         string      `json:"html_content"`
}

func (q *Queries) UpdateSiteGeneration(ctx context.Context, arg UpdateSiteGenerationParams) (Site, error) {
	row := q.db.QueryRow(ctx, updateSiteGeneration,
		arg.UserID,
		arg.BusinessName,
		arg.BusinessDescription,
		arg.ColorPalette,
		arg.HtmlContent,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.BusinessName,
		&i.BusinessDescription,
		&i.ColorPalette,
		&i.HtmlContent,
		&i.Published,
		&i.CustomDomain,
		&i.GenerationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSitePublished = `-- name: UpdateSitePublished :one
UPDATE sites SET published = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, slug, business_name, business_description, color_palette, html_content, published, custom_domain, generation_count, created_at, updated_at
`

type UpdateSitePublishedParams struct {
	ID        pgtype.UUID `json:"id"`
	Published bool        `json:"published"`
}

func (q *Queries) UpdateSitePublished(ctx context.Context, arg UpdateSitePublishedParams) (Site, error) {
	row := q.db.QueryRow(ctx, updateSitePublished, arg.ID, arg.Published)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.BusinessName,
		&i.BusinessDescription,
		&i.ColorPalette,
		&i.HtmlContent,
		&i.Published,
		&i.CustomDomain,
		&i.GenerationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
