// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSite = `-- name: CreateSite :one
INSERT INTO sites (user_id, slug, business_name, business_description, color_palette)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, slug, business_name, business_description, color_palette, html_content, published, custom_domain, generation_count, created_at, updated_at
`

type CreateSiteParams struct {
	UserID              pgtype.UUID `json:"user_id"`
	Slug                string      `json:"slug"`
	BusinessName        string      `json:"business_name"`
	BusinessDescription string      `json:"business_description"`
	ColorPalette        string      `json:"color_palette"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.UserID,
		arg.Slug,
		arg.BusinessName,
		arg.BusinessDescription,
		arg.ColorPalette,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.BusinessName,
		&i.BusinessDescription,
		&i.ColorPalette,
		&i.HtmlContent,
		&i.Published,
		&i.CustomDomain,
		&i.GenerationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteBySlug = `-- name: GetSiteBySlug :one
SELECT id, user_id, slug, business_name, business_description, color_palette, html_content, published, custom_domain, generation_count, created_at, updated_at FROM sites WHERE slug = $1
`

func (q *Queries) GetSiteBySlug(ctx context.Context, slug string) (Site, error) {
	row := q.db.QueryRow(ctx, getSiteBySlug, slug)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.BusinessName,
		&i.BusinessDescription,
		&i.ColorPalette,
		&i.HtmlContent,
		&i.Published,
		&i.CustomDomain,
		&i.GenerationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteByUserID = `-- name: GetSiteByUserID :one
SELECT id, user_id, slug, business_name, business_description, color_palette, html_content, published, custom_domain, generation_count, created_at, updated_at FROM sites WHERE user_id = $1
`

func (q *Queries) GetSiteByUserID(ctx context.Context, userID pgtype.UUID) (Site, error) {
	row := q.db.QueryRow(ctx, getSiteByUserID, userID)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.BusinessName,
		&i.BusinessDescription,
		&i.ColorPalette,
		&i.HtmlContent,
		&i.Published,
		&i.CustomDomain,
		&i.GenerationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSiteContent = `-- name: UpdateSiteContent :one
UPDATE sites
SET html_content      = $2,
    published         = $3,
    generation_count  = generation_count + 1,
    updated_at        = NOW()
WHERE id = $1
RETURNING id, user_id, slug, business_name, business_description, color_palette, html_content, published, custom_domain, generation_count, created_at, updated_at
`

type UpdateSiteContentParams struct {
	ID          pgtype.UUID `json:"id"`
	HtmlContent string      `json:"html_content"`
	Published   bool        `json:"published"`
}

func (q *Queries) UpdateSiteContent(ctx context.Context, arg UpdateSiteContentParams) (Site, error) {
	row := q.db.QueryRow(ctx, updateSiteContent, arg.ID, arg.HtmlContent, arg.Published)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.BusinessName,
		&i.BusinessDescription,
		&i.ColorPalette,
		&i.HtmlContent,
		&i.Published,
		&i.CustomDomain,
		&i.GenerationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSiteCustomDomain = `-- name: UpdateSiteCustomDomain :one
UPDATE sites SET custom_domain = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, slug, business_name, business_description, color_palette, html_content, published, custom_domain, generation_count, created_at, updated_at
`

type UpdateSiteCustomDomainParams struct {
	ID           pgtype.UUID `json:"id"`
	CustomDomain pgtype.Text `json:"custom_domain"`
}

func (q *Queries) UpdateSiteCustomDomain(ctx context.Context, arg UpdateSiteCustomDomainParams) (Site, error) {
	row := q.db.QueryRow(ctx, updateSiteCustomDomain, arg.ID, arg.CustomDomain)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.BusinessName,
		&i.BusinessDescription,
		&i.ColorPalette,
		&i.HtmlContent,
		&i.Published,
		&i.CustomDomain,
		&i.GenerationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
