// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSubscriptionByUserID = `-- name: GetSubscriptionByUserID :one
SELECT id, user_id, vindi_customer_id, vindi_subscription_id, status, current_period_end, created_at, updated_at FROM subscriptions WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetSubscriptionByUserID(ctx context.Context, userID pgtype.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByUserID, userID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VindiCustomerID,
		&i.VindiSubscriptionID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :one
UPDATE subscriptions SET status = $2, updated_at = NOW()
WHERE vindi_subscription_id = $1
RETURNING id, user_id, vindi_customer_id, vindi_subscription_id, status, current_period_end, created_at, updated_at
`

type UpdateSubscriptionStatusParams struct {
	VindiSubscriptionID pgtype.Int4 `json:"vindi_subscription_id"`
	Status              string      `json:"status"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionStatus, arg.VindiSubscriptionID, arg.Status)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VindiCustomerID,
		&i.VindiSubscriptionID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSubscription = `-- name: UpsertSubscription :one
INSERT INTO subscriptions (user_id, vindi_customer_id, vindi_subscription_id, status, current_period_end, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (user_id) DO UPDATE SET
    vindi_customer_id     = EXCLUDED.vindi_customer_id,
    vindi_subscription_id = EXCLUDED.vindi_subscription_id,
    status                = EXCLUDED.status,
    current_period_end    = EXCLUDED.current_period_end,
    updated_at            = NOW()
RETURNING id, user_id, vindi_customer_id, vindi_subscription_id, status, current_period_end, created_at, updated_at
`

type UpsertSubscriptionParams struct {
	UserID              pgtype.UUID        `json:"user_id"`
	VindiCustomerID     pgtype.Int4        `json:"vindi_customer_id"`
	VindiSubscriptionID pgtype.Int4        `json:"vindi_subscription_id"`
	Status              string             `json:"status"`
	CurrentPeriodEnd    pgtype.Timestamptz `json:"current_period_end"`
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.UserID,
		arg.VindiCustomerID,
		arg.VindiSubscriptionID,
		arg.Status,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VindiCustomerID,
		&i.VindiSubscriptionID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
